### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-pc3w0#5]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by ravi0900** [comment]
![image](https://user-images.githubusercontent.com/65914575/182563937-a737b9fc-03fa-4c2b-8bf6-886b80161721.png)
bug fix closing this issue.
